# Generated by Django 5.0.6 on 2024-05-24 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='데이터가 생성 된 날짜 입니다.', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='데이터가 수정 된 날짜 입니다.', verbose_name='수정 일시')),
                ('available', models.IntegerField(default=0, verbose_name='최대 참석 가능 수강생 인원')),
                ('attend_code', models.CharField(default=0, max_length=8, verbose_name='강의장 참석을 위한 코드')),
                ('x_room_id', models.CharField(default=0, max_length=16, verbose_name='강의장 ID')),
                ('is_closed', models.BooleanField(default=True, verbose_name='강의장 종료')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'status': 'student'}, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.OneToOneField(limit_choices_to={'status': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
